export const USER_ACTIONS_TYPE = {
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_USER_LIST: 'SET_USER_LIST',
    SET_OCCURRENCES: 'SET_OCCURRENCES',
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    SET_FILTERED: 'SET_FILTERED',
    SET_SORTING: 'SET_SORTING',
    REMOVE: 'REMOVE',
};